LineLength:
  Max: 100  

MethodLength:
  Max: 15

AbcSize:
  Max: 23

Metrics/AbcSize: 
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - './cryptographer_test.rb'

FrozenStringLiteralComment: 
  Enabled: false